### PR TITLE
fix: unsigned number maximum

### PR DESCRIPTION
**Pull request by jinker**

### CODE REVIEW

**Comment by duartealexf** [comment]
Hi @jinker thank you so much for contributing!

Could you please run `npm run test:update` to update test result files? I'm surprised on how the tests passed without this.

Cheers.

**Comment by jinker** [comment]
> Hi @jinker thank you so much for contributing!
> 
> Could you please run `npm run test:update` to update test result files? I'm surprised on how the tests passed without this.
> 
> Cheers.

Test case added.

**Comment by duartealexf** [comment]
@jinker thank you, i will take a look at this as soon as possible, so we can discuss about it.

Cheers.

**Comment by duartealexf** [comment]
Hi @jinker. I noticed you did two things:

1. Fixed the 'onUpdate' which was missing in compact JSON output;
2. Fixed the unsigned numbers in JSON schema output.

The first one was fixed in version 3.1.1, which was pointed out on issue #45.
The second one i am fixing now on version 3.1.2. Thank you for noticing it :)

As for this PR...
I just don't see why adding more properties like "default_exp" and "x-default-exp" for such a change, replacing current ones and causing breaking changes. For that i'd have to release v4.0.0.
So i can't merge this PR because of the breaking changes for just a fix.

But still, thank you for contributing and pointing out these two errors :)

**Pull request closed without merging**
